Dev model
WisdomWorks/ecode-be pull request #2
Opened 2024-01-21 14:52 UTC by HoXuanHieu

please update model into dev-branch

2024-01-22 13:01 UTC, th4tkh13m commented
Not done yet. Should not merge.

2024-01-24 15:27 UTC, th4tkh13m requested changes

2024-01-24 15:27 UTC, th4tkh13m commented on src/main/java/com/example/codeE/model/user/StudentEnrollment.java
> +import lombok.*;
?

2024-01-24 15:28 UTC, th4tkh13m requested changes

2024-01-24 15:28 UTC, th4tkh13m commented on src/main/java/com/example/codeE/model/user/Submission.java
> +    private String description ;
Can you reformat please

2024-01-24 15:37 UTC, th4tkh13m requested changes

2024-01-24 15:37 UTC, th4tkh13m commented on src/main/java/com/example/codeE/model/group/Group.java
> +    //primary key
Remove this

2024-01-25 13:05 UTC, HoXuanHieu commented
làm ơn

2024-01-25 13:25 UTC, th4tkh13m approved these changes
lgtm

2024-01-25 13:26 UTC, merged