feat: saving exercise in mySql
WisdomWorks/ecode-be pull request #27
Opened 2024-02-10 14:23 UTC by Noro911

2024-02-12 01:30 UTC, th4tkh13m requested changes

2024-02-12 01:30 UTC, th4tkh13m commented on src/main/java/com/example/codeE/service/exercise/MSExerciseImpl.java
> +    public MSExercise saveExerciseToMySql(MSExercise msExercise) {
Can you change the name of this method to `saveExercise`?

2024-02-12 01:30 UTC, th4tkh13m commented on src/main/java/com/example/codeE/model/course/Course.java
> +    @NotBlank(message = "Updated date is required")
Do we need this? In Database, the value is default to `NOW()`, so we do not need to set this value.

2024-02-12 01:30 UTC, th4tkh13m commented on src/main/java/com/example/codeE/model/course/Course.java
> +        updatedDate = DateTimeUtil.format(now);
Unnecessary since DB already handles this.

2024-02-12 01:30 UTC, th4tkh13m commented on src/main/java/com/example/codeE/model/course/Course.java
> +        updatedDate = DateTimeUtil.format(LocalDateTime.now());
Unnecessary since DB already handles this.

2024-02-12 01:30 UTC, th4tkh13m commented on src/main/java/com/example/codeE/repository/MSExerciseRepository.java
> +                    + "WHERE c.courseId = ?1")
Are you sure that this query is correct?

2024-02-12 01:30 UTC, th4tkh13m commented on src/main/java/com/example/codeE/request/exercise/DeleteExerciseRequest.java
> +    @Pattern(regexp = "^(quizz|essay|code)$", message = "Exercise type should be quizz, essay, or code")
spelling mistake :>

2024-02-12 01:34 UTC, th4tkh13m commented
@Noro911, apparently, there are some updates to the Database Schema.

Noticeable changes:
1. We decided to move Exercises to MongoDB. Right now, the schema is still based on the DB, but we can clear that out in the next meeting.
2. Introducing a new table called topic view permission. This table allows teachers to set which group can view which topic. (Similar with material)

Therefore, please read the DDL file in the DB repo. Don't hesitate to mention me if there are any questions.

2024-02-17 13:26 UTC, HoXuanHieu approved these changes

2024-02-17 13:26 UTC, HoXuanHieu commented on src/main/java/com/example/codeE/model/course/Course.java
> +import jakarta.persistence.*;
please restrict using * when import lib.

2024-02-19 12:11 UTC, merged