Ww 67
WisdomWorks/ecode-be pull request #29
Opened 2024-02-16 17:37 UTC by TungPhan2808

- Add update and delete user by userId feature
- Improve response return of 
- Fix injection in UserController

2024-02-17 13:29 UTC, HoXuanHieu commented on src/main/java/com/example/codeE/controller/exception/ResourceNotFoundException.java
what is class use for?

2024-02-18 08:15 UTC, TungPhan2808 commented on src/main/java/com/example/codeE/controller/exception/ResourceNotFoundException.java
Just for handle exception

2024-02-26 11:43 UTC, Noro911 requested changes

2024-02-29 02:13 UTC, Noro911 requested changes

2024-02-29 02:13 UTC, Noro911 commented on src/main/java/com/example/codeE/model/user/User.java
> +import com.example.codeE.validator.id.ExistingId;
Where is this used?

2024-02-29 15:55 UTC, Noro911 approved these changes

2024-03-01 14:52 UTC, th4tkh13m approved these changes

2024-03-01 14:55 UTC, closed without merging